const CHANGE_STAT_SCORE = "CHANGE_STAT_SCORE"
const GET_STAT = "GET_STAT"
const CHANGE_DIST = "CHANGE_DIST"
const CHANGE_ATTR = "CHANGE_ATTR"
const GET_ATTR = "GET_ATTR"

export default {
    CHANGE_STAT_SCORE,
    CHANGE_DIST,
    CHANGE_ATTR,
    GET_ATTR,
    GET_STAT
}