const ADD_BOND = "ADD_BOND"
const CHANGE_BOND = "CHANGE_BOND"
const CHANGE_BOND_SCORE = "CHANGE_BOND_SCORE"
const DELETE_BOND = "DELETE_BOND"
const GET_BOND = "GET_BOND"

const CHANGE_MOTIV = "CHANGE_MOTIV"
const GET_MOTIV = "GET_MOTIV"

export default {
    ADD_BOND,
    CHANGE_BOND,
    CHANGE_BOND_SCORE,
    DELETE_BOND,
    GET_BOND,

    CHANGE_MOTIV,
    GET_MOTIV
}