const CHANGE_MOD = "CHANGE_MOD"
const CHANGE_CON = "CHANGE_CON"
const CHECK_ADDITION = "CHECK_ADDITION"
const CHANGE_POINTS = "SKILL_POINTS"
const CHANGE_ADDITION_POINTS = "CHANGE_ADDITION_POINTS"
const ADD_SKILL = "ADD_SKILL"
const DEL_SKILL = "DEL_SKILL"
const CHANGE_OTHER = "CHANGE_OTHER"


export default {
    ADD_SKILL,
    DEL_SKILL,
    CHANGE_OTHER,

    CHANGE_ADDITION_POINTS,
    CHECK_ADDITION,
    CHANGE_MOD,
    CHANGE_CON,
    CHANGE_POINTS
}